version: 0

type: "multi-grpc"
worker:
  container: "tensorflow/tensorflow:1.12.0-gpu-py3"
  command: "python mnist.py"
  machine-type: "K80"
  count: 3
parameter-server:
  container: "tensorflow/tensorflow:1.12.0-gpu-py3"
  command: "python mnist.py"
  machine-type: "K80"
  count: 1
