version: 0

type: "multi-grpc"
ports: "5000"
paths:
  workdir: "/home/playground"
  artifacts: "/var/ml/artifacts"
worker:
  container: "tensorflow/tensorflow:1.8.0-gpu"
  command: "nvidia-smi"
  machine-type: "K80"
  count: 1
parameter-server:
  container: "tensorflow/tensorflow:1.8.0-gpu"
  command: "nvidia-smi"
  machine-type: "K80"
  count: 1
